---
baseurl: "https://magicluo.com/"
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
languageCode: "zh-cn"
title: "Laurence Luo" 
theme: "beautifulhugo"
metaDataFormat: "yaml"
subtitle: "I can help you building Cloud Native confidence"
dateFormat: "January 2, 2006"
description: "Cloud Native and Big Data"
#
#algolia:
#  index: "rootsonjgc-hugo"
#  key: "061f6cd08c1f001f39ea2dd918330b58"
#  appID: "X4YB3WOBNV"
---
